In [2]:
!pip install pandas

In [3]:
import numpy as np
import pandas as pd
from sklearn import linear_model

In [4]:
df=pd.read_csv('detailedhouseprice.csv')
df

area  bedroom   age   price
0  2600       3.0   20  550000
1  3000       4.0   15  565000
2  3200       NaN   18  610000
3  3600       3.0   30  595000
4  4000       5.0    8  760000

In [15]:
import math
df.bedroom.mean()

AttributeError: 'DataFrame' object has no attribute 'bedroom'

In [16]:
df=pd.read_csv('detailedhouseprice.csv')
df

area  bedroom  age   price
0  2600      3.0   20  550000
1  3000      4.0   15  565000
2  3200      NaN   18  610000
3  3600      3.0   30  595000
4  4000      5.0    8  760000

In [17]:
import math
df.bedroom.median()

3.5

In [18]:
median_bedroom=math.floor(df.bedroom.median())
median_bedroom

3

In [19]:
df.bedroom.fillna(median_bedroom)

0    3.0
1    4.0
2    3.0
3    3.0
4    5.0
Name: bedroom, dtype: float64

In [20]:
df

area  bedroom  age   price
0  2600      3.0   20  550000
1  3000      4.0   15  565000
2  3200      NaN   18  610000
3  3600      3.0   30  595000
4  4000      5.0    8  760000

In [21]:
df.bedroom=df.bedroom.fillna(median_bedroom)

In [22]:
df

area  bedroom  age   price
0  2600      3.0   20  550000
1  3000      4.0   15  565000
2  3200      3.0   18  610000
3  3600      3.0   30  595000
4  4000      5.0    8  760000

In [23]:
reg=linear_model.LinearRegression()


In [24]:
reg.fit(df[['area','bedroom','age']],df.price)

LinearRegression()

In [25]:
reg.coef_

array([   137.25, -26025.  ,  -6825.  ])

In [26]:
reg.intercept_

383724.9999999998

In [27]:
reg.predict([[3000,3,40]])

C:\Users\Ayan Maity\miniconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([444400.])

In [28]:
reg.predict([[2500,4,5]])

C:\Users\Ayan Maity\miniconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([588625.])